### ISSUE TITLE
[BUG] Surround didn't work (apart from Burrow option).

### ISSUE THREAD

**Issue by cow167** [3arthh4ckDevelopment/3arthh4ck-Fabric#29]

**Comment by nukiz** [comment]
known issue, surround places but only partially and not completely

**Comment by nukiz** [comment]
actually, this was fixed in commit https://github.com/3arthh4ckDevelopment/3arthh4ck-Fabric/commit/2abf4f9f3831302275c513212b4e0e28eb0f8183
