### ISSUE TITLE
[BUG] Incompatible with meteor

### ISSUE THREAD

**Issue by cow167** [3arthh4ckDevelopment/3arthh4ck-Fabric#39]

**Comment by nukiz** [comment]
Thanks for the report. For future issues, please upload a crash report or something of the sorts so I can diagnose the issue by just reading the issue. Fixed it in commit https://github.com/3arthh4ckDevelopment/3arthh4ck-Fabric/commit/a098941df9b59ded4aa5e90cfaa6e2d9558f1599.
