### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by younojj** [3arthh4ckDevelopment/3arthh4ck-Fabric#55]
can i use it in 1.20.1？

**Comment by Ai2473** [comment]
No, you can't load it using 1.20.1, but if you need a 1.20.1 server you can use viafabricplus

**Comment by younojj** [comment]
thx

**Comment by nukiz** [comment]
You can use it on servers running version 1.20.1 with either [this](https://modrinth.com/mod/viafabric) or [this](https://modrinth.com/mod/viafabricplus) mod.

Alternatively, you can change some parameters in the `gradle.properties` file and build the client again yourself to run it on version 1.20.1.
