### ISSUE TITLE
this client sucks

### ISSUE THREAD

**Issue by lolwut2** [3arthh4ckDevelopment/3arthh4ck-Fabric#58]
**Describe the bug**  
The client is badly produced.

**To Reproduce**  

**Expected behavior**  
No expected behaviour (because it doesnt work)

**Crashlog**  
If you crashed and you don't provide a crashlog I will ignore you!

**Additional context**  

**Checklist**
- [x] I know how to properly use check boxes.
- [ ] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [ ] I followed the issue template.

**Comment by lolwut2** [comment]
it hasnt gotten any better

**Comment by nukiz** [comment]
known issue
