### ISSUE TITLE
[FEATURE] PLEASE PORT TO 1.21.1!!! I NEED IT URGENTLY PLEASE PLEASE PLEASE!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by 3vZVVm6V9A3O877TUqQD** [3arthh4ckDevelopment/3arthh4ck-Fabric#69]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ai2473** [comment]
What do you need it for lmao

**Comment by Smug2f** [comment]
Why 1.21.1 instead of 1.21 ? Do you just want it on the latest version just for the sake of it?

**Comment by CatCod6r** [comment]
Bro where this retards coming from

**Comment by Zane2b2t** [comment]
> I need it for a server called CONSTANTIAM

viafabricplus

**Comment by Zane2b2t** [comment]
> Can we close this, a dev is now confirmed to be working on this.

you are thread owner
